user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 50
gravatar:
  size: 80
remember_me:
  checked: "1"
seed:
  min_age: 18
  max_age: 65
  male: 0
  female: 1
  users_to_create: 99
fixtures:
  users_to_create: 30
password: "password"
expired: 2
no_reply_mail: "noreply@thamdavies.com"
